version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: zulficore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass Ph4nt0m4+4 --appendonly yes
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=Ph4nt0m4+4
    networks:
      - zulficore-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  zulficore-network:
    driver: bridge